name: Deploy GitaSakha API

on:
  push:
    branches: [ main, development ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          pip install pytest
          pytest -v
          
      - name: Set environment name
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENV_NAME=production" >> $GITHUB_ENV
            echo "SERVICE_NAME=gitasakha-api" >> $GITHUB_ENV
          else
            echo "ENV_NAME=development" >> $GITHUB_ENV
            echo "SERVICE_NAME=gitasakha-api-dev" >> $GITHUB_ENV
          fi
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: project-gita-sakha
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          
      - name: Authenticate Docker to Google Cloud
        run: gcloud auth configure-docker
          
      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/project-gita-sakha/gitasakha-api:${{ github.sha }} .
          docker push gcr.io/project-gita-sakha/gitasakha-api:${{ github.sha }}
          
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image gcr.io/project-gita-sakha/gitasakha-api:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --memory 1Gi \
            --cpu 1 \
            --set-env-vars="API_KEY=${{ secrets.API_KEY }},ENVIRONMENT=${{ env.ENV_NAME }}" \
            --allow-unauthenticated
