name: Deploy GitaSakha API

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          pip install pytest
          echo "Skipping tests temporarily"
          # PYTHONPATH=. pytest -v || true
          
      - name: Set environment name
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENV_NAME=production" >> $GITHUB_ENV
            echo "SERVICE_NAME=gitasakha-api" >> $GITHUB_ENV
          else
            echo "ENV_NAME=development" >> $GITHUB_ENV
            echo "SERVICE_NAME=gitasakha-api-dev" >> $GITHUB_ENV
          fi
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: project-gita-sakha
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          
      - name: Build and Push to Google Container Registry
        uses: google-github-actions/build-push-gcr@v1
        with:
          project_id: project-gita-sakha
          registry: gcr.io
          image_name: gitasakha-api
          image_tag: ${{ github.sha }}
          
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SERVICE_NAME }}
          image: gcr.io/project-gita-sakha/gitasakha-api:${{ github.sha }}
          region: us-central1
          env_vars: |
            API_KEY=${{ secrets.API_KEY }}
            ENVIRONMENT=${{ env.ENV_NAME }}
          memory: 1Gi
          cpu: 1
          allow_unauthenticated: true